# Generated by Django 5.2.10 on 2026-01-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipmentneed_medicalessential_donorprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='phone',
        ),
    ]
