# Generated by Django 4.2.26 on 2025-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_donorprofile_user_donorprofile_donor_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
