# Generated by Django 5.2.10 on 2026-01-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_donorprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
