# Generated by Django 4.2.18 on 2025-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donorprofile_first_name_donorprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='donor_module',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('hospital', 'Hospital'), ('medical_essential', 'Medical Essential')], max_length=20, null=True),
        ),
    ]
