# Generated by Django 5.2.10 on 2026-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donationrequest_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonor',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
