# Generated by Django 4.2.18 on 2025-12-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donorprofile_donor_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('equipment_type', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic Equipment'), ('SURGICAL', 'Surgical Equipment'), ('MONITORING', 'Monitoring Equipment'), ('LIFE_SUPPORT', 'Life Support Equipment'), ('STERILIZATION', 'Sterilization Equipment'), ('FURNITURE', 'Hospital Furniture'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('warranty_period_months', models.PositiveIntegerField(default=12, help_text='Warranty period in months')),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medical_equipment/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True, help_text='New or used equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('SUPPLIER', 'Medical Supplier'), ('DISTRIBUTOR', 'Distributor'), ('RETAILER', 'Retailer'), ('MANUFACTURER', 'Manufacturer'), ('OTHER', 'Other')], default='SUPPLIER', max_length=50)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, help_text='Business license/registration number', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100)),
                ('api_key', models.CharField(db_index=True, help_text='API key for authentication', max_length=64, unique=True)),
                ('api_key_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified supplier status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_essential_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('STORE', 'Medical Store'), ('EQUIPMENT', 'Equipment')], max_length=20)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.medicalessential')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicines'), ('SUPPLIES', 'Medical Supplies'), ('CONSUMABLES', 'Consumables'), ('INSTRUMENTS', 'Instruments'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='unit', help_text='e.g., box, pack, bottle', max_length=50)),
                ('expiry_date', models.DateField(blank=True, help_text='For medicines with expiry', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medical_store/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_prescription_required', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='core.medicalessential')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('STORE', 'Store Product'), ('EQUIPMENT', 'Equipment')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicalequipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.medicalorder')),
                ('store_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicalstoreproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_products', to='core.medicalessential'),
        ),
    ]
