# Generated by Django 5.2.10 on 2026-01-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientvisit_patient_patientvisit_payment_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalessential',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='medicalessential',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicalessential',
            name='phone',
        ),
        migrations.AddField(
            model_name='medicalessential',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_essentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
