# Generated by Django 5.2.10 on 2026-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_medicalessential_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='patient_name',
            field=models.CharField(blank=True, help_text='Name of the patient the donation is for', max_length=200),
        ),
    ]
