# Generated by Django 5.2.10 on 2026-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donationrequest_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='request_type',
            field=models.CharField(choices=[('BLOOD', 'Blood'), ('ORGAN', 'Organ'), ('PLATELETS', 'Platelets')], default='BLOOD', max_length=16),
        ),
    ]
