# Generated by Django 5.2.10 on 2026-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_donationrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='confirmed_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='fruity_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='rewards',
            field=models.TextField(blank=True, help_text='Rewards given to the donor'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='star_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Hospital staff staff notes'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ARRIVED', 'Arrived'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
