# Generated by Django 5.2.10 on 2026-01-30 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donationrequest_confirmed_arrival_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='current_stars',
            field=models.PositiveIntegerField(default=0, help_text='Stars earned since last reward reset (0-50)'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_money_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total monetary rewards earned (Rs)', max_digits=10),
        ),
        migrations.CreateModel(
            name='DonorCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=20)),
                ('is_used', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
