# Generated by Django 5.2.10 on 2026-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_donorprofile_current_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Donor's age in years", null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Donor's weight in kg", max_digits=5, null=True),
        ),
    ]
