# Generated by Django 5.2.10 on 2026-01-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donorprofile_age_donorprofile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or rescheduling'),
        ),
    ]
