# Generated by Django 5.2.10 on 2026-01-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_appointment_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonor',
            name='accepted_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_organ_pledges', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='hospital_message',
            field=models.TextField(blank=True, help_text='Message from the hospital upon acceptance'),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Hospital Accepted'), ('COMMITTED', 'Committed'), ('BODY_RECEIVED', 'Body Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
