# Generated by Django 5.2.10 on 2026-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organdonor_accepted_by_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='health_report',
            field=models.FileField(blank=True, null=True, upload_to='health_reports/'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='health_status',
            field=models.CharField(blank=True, help_text='Summary of health assessment', max_length=100, null=True),
        ),
    ]
