# Generated by Django 5.2.10 on 2026-02-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='verification_document',
            field=models.CharField(blank=True, help_text='URL or path to uploaded verification document', max_length=500, null=True),
        ),
    ]
