# Generated by Django 5.2.10 on 2026-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_eventregistration_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonor',
            name='body_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to family/contact', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMING', 'Coming'), ('NOT_COMING', 'Not Coming'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='organdonor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Hospital Accepted'), ('COMMITTED', 'Committed'), ('BODY_RECEIVED', 'Body Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
