# Generated by Django 5.2.10 on 2026-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_organdonor_body_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
