# Generated by Django 5.2.10 on 2026-02-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
