# Generated by Django 5.2.10 on 2026-02-04 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_donorprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFIntegrityLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_id', models.CharField(help_text='Unique ID for each download session', max_length=100, unique=True)),
                ('pdf_hash', models.CharField(help_text='SHA-256 hash of the generated PDF content', max_length=64)),
                ('previous_block_hash', models.CharField(blank=True, help_text='Hash of the preceding block', max_length=64, null=True)),
                ('block_hash', models.CharField(help_text='Hash of this block (prev_hash + data)', max_length=64)),
                ('nonce', models.PositiveIntegerField(default=0, help_text='Proof-of-work simulation value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
