# Generated by Django 5.2.10 on 2026-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pdfintegrityledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='latest_report_id',
            field=models.CharField(blank=True, help_text='Reference to the last generated blockchain report ID', max_length=100, null=True),
        ),
    ]
