# Generated by Django 5.2.10 on 2026-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_donorprofile_latest_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfintegrityledger',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The actual PDF report stored for verification', null=True, upload_to='integrity_ledger_reports/'),
        ),
    ]
