# Generated by Django 5.2.10 on 2026-02-05 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pdfintegrityledger_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonor',
            name='blockchain_record',
            field=models.ForeignKey(blank=True, help_text='Immutable ledger record for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_pledges', to='core.pdfintegrityledger'),
        ),
        migrations.AddField(
            model_name='organdonor',
            name='pledge_report',
            field=models.FileField(blank=True, null=True, upload_to='organ_pledges/'),
        ),
    ]
