# Generated by Django 5.2.10 on 2026-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organdonor_blockchain_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfintegrityledger',
            name='report_type',
            field=models.CharField(choices=[('BLOOD', 'Blood Donation Report'), ('ORGAN_PLEDGE', 'Organ Pledge Report'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
