# Generated by Django 5.2.10 on 2026-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pdfintegrityledger_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfintegrityledger',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True if this is the latest valid version for this donor'),
        ),
        migrations.AlterField(
            model_name='organdonor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Hospital Accepted'), ('REPORT_VERIFIED', 'Report Verified'), ('COMMITTED', 'Committed'), ('BODY_RECEIVED', 'Body Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
