# Generated by Django 5.2.10 on 2026-02-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pdfintegrityledger_is_active_alter_organdonor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceaseddonorrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_donor_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
