# Generated by Django 5.2.10 on 2026-02-05 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_deceaseddonorrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceaseddonorrequest',
            name='hospital_referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deceased_requests', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='deceaseddonorrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deceased_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
