# Generated by Django 5.2.10 on 2026-02-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_deceaseddonorrequest_hospital_referred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='medical_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.medicalorder'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='equipment_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.equipmentorder'),
        ),
    ]
