# Generated by Django 5.2.10 on 2026-02-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_invoice_medical_order_alter_invoice_equipment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
