# Generated by Django 5.2.10 on 2026-02-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_medicalorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_viewed_by_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
