# Generated by Django 5.2.10 on 2026-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_invoice_is_viewed_by_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorder',
            name='actual_shipping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='estimated_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating given by hospital (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
