# Generated by Django 5.2.10 on 2026-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_medicalorder_actual_shipping_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='time_schedule',
            field=models.CharField(blank=True, help_text='Doctor availability schedule (e.g. Mon-Fri 10AM-4PM)', max_length=500),
        ),
    ]
