# Generated by Django 5.2.10 on 2026-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_doctor_time_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20),
        ),
    ]
