# Generated by Django 5.2.10 on 2026-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_appointment_confirmed_arrival_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_purpose',
            field=models.CharField(choices=[('BLOOD_DONATION', 'Blood Donation'), ('PLATELET_DONATION', 'Platelet Donation'), ('ORGAN_DONATION', 'Organ Donation'), ('CONSULTATION', 'Consultation'), ('OPERATION', 'Operation/Surgery'), ('CHECKUP', 'Regular Checkup'), ('EMERGENCY', 'Emergency Treatment'), ('FOLLOWUP', 'Follow-up Visit'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
