# Generated by Django 5.2.10 on 2026-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_reaching',
            field=models.BooleanField(default=False, help_text='Donor signaled they are on the way'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='next_consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_data',
            field=models.JSONField(blank=True, help_text='Structured prescription details', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reaching_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
