# Generated by Django 5.2.10 on 2026-02-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_medicalorder_appointment_alter_medicalorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, help_text='Location or address for ambulance', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('ACCEPTED', 'Ambulance Dispatched'), ('ARRIVED', 'Ambulance Arrived'), ('COMPLETED', 'Patient Admitted (Life Saved)'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_rewarded', models.BooleanField(default=False, help_text='True if the reporter has received a star for this')),
                ('accident_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='core.accidentalert')),
                ('emergency_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='core.emergencyneed')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='core.hospital')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
