# Generated by Django 5.2.10 on 2026-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_ambulancerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='accident_alert',
        ),
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='emergency_need',
        ),
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='emergencyneed',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AccidentAlert',
        ),
        migrations.DeleteModel(
            name='AmbulanceRequest',
        ),
        migrations.DeleteModel(
            name='EmergencyNeed',
        ),
    ]
