# Generated by Django 5.2.10 on 2026-02-09 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_ambulancerequest_accident_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(help_text='Accident location', max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('accident_time', models.DateTimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('hospital_referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accident_alerts', to='core.hospital')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('need_type', models.CharField(choices=[('BLOOD', 'Blood'), ('PLATELETS', 'Platelets'), ('ORGAN', 'Organ'), ('FUNDS', 'Funds'), ('OTHER', 'Other')], default='BLOOD', max_length=16)),
                ('required_blood_group', models.CharField(blank=True, max_length=3)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('needed_by', models.DateTimeField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, help_text='Patient poster/image for sharing', null=True, upload_to='emergency_posters/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, help_text='Location or address for ambulance', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('ACCEPTED', 'Ambulance Dispatched'), ('ARRIVED', 'Ambulance Arrived'), ('COMPLETED', 'Patient Admitted (Life Saved)'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_rewarded', models.BooleanField(default=False, help_text='True if the reporter has received a star for this')),
                ('accident_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='core.accidentalert')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='core.hospital')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to=settings.AUTH_USER_MODEL)),
                ('emergency_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='core.emergencyneed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
