# Generated by Django 5.2.10 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_accidentalert_emergencyneed_ambulancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyneed',
            name='organ_type',
            field=models.CharField(blank=True, choices=[('HEART', 'Heart'), ('LIVER', 'Liver'), ('KIDNEY', 'Kidney'), ('LUNGS', 'Lungs'), ('PANCREAS', 'Pancreas'), ('INTESTINE', 'Intestine'), ('TISSUE', 'Tissue'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergencyneed',
            name='referral_phone',
            field=models.CharField(blank=True, help_text='Contact number for referral/informant', max_length=32, null=True),
        ),
    ]
