# Generated by Django 5.2.10 on 2026-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_emergencyneed_organ_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyneed',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monetary reward for donors/informants', max_digits=10, null=True),
        ),
    ]
