# Generated by Django 5.2.10 on 2026-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_emergencyneed_accepted_by_emergencyneed_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorder',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
