# Generated by Django 5.2.10 on 2026-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_medicalorder_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalneed',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Patient poster/image', null=True, upload_to='hospital_needs/'),
        ),
        migrations.AlterField(
            model_name='medicalorder',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
