# Generated by Django 5.2.10 on 2026-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_hospitalneed_poster_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('SCHEDULE_CONFIRMED', 'Schedule Confirmed'), ('REACHING', 'Reaching'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32),
        ),
    ]
