# Generated by Django 5.2.10 on 2026-02-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_donationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='emergency_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='core.emergencyneed'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='hospital_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='core.hospitalneed'),
        ),
    ]
