# Generated by Django 5.2.10 on 2026-02-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_donationrequest_emergency_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='core.hospital'),
        ),
    ]
