# Generated by Django 5.2.10 on 2026-02-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_donationrequest_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancerequest',
            name='accident_alert',
        ),
        migrations.DeleteModel(
            name='AccidentAlert',
        ),
    ]
