# Generated by Django 5.2.10 on 2026-02-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_ambulancerequest_accident_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentneed',
            name='is_confirmed_by_supplier',
            field=models.BooleanField(default=False, help_text='Set to True when supplier creates the item from this request'),
        ),
        migrations.AddField(
            model_name='equipmentneed',
            name='requested_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_needs', to='core.medicalessential'),
        ),
        migrations.AddField(
            model_name='equipmentneed',
            name='suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price suggested by hospital or supplier during the request process', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='created_from_request',
            field=models.ForeignKey(blank=True, help_text='Link to the original hospital request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to='core.equipmentneed'),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='complaint_message',
            field=models.TextField(blank=True, help_text='Message if item not received after payment'),
        ),
        migrations.AddField(
            model_name='medicalorder',
            name='is_complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalstoreproduct',
            name='created_from_request',
            field=models.ForeignKey(blank=True, help_text='Link to the original hospital request if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to='core.equipmentneed'),
        ),
    ]
