# Generated by Django 5.2.10 on 2026-02-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_equipmentneed_is_confirmed_by_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentneed',
            name='equipment_type',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic Equipment'), ('SURGICAL', 'Surgical Equipment'), ('MONITORING', 'Monitoring Equipment'), ('LIFE_SUPPORT', 'Life Support Equipment'), ('STERILIZATION', 'Sterilization Equipment'), ('FURNITURE', 'Hospital Furniture'), ('MEDICINE', 'Medicines'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
