# Generated by Django 5.2.10 on 2026-02-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_equipmentneed_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorder',
            name='equipment_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_orders_from_need', to='core.equipmentneed'),
        ),
    ]
