# Generated by Django 5.2.10 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_medicalorder_equipment_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalneed',
            name='location_details',
            field=models.CharField(blank=True, help_text='Specific place/ward within the hospital', max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalneed',
            name='patient_contact',
            field=models.CharField(blank=True, help_text='Contact number for the patient/attendant', max_length=32),
        ),
        migrations.AddField(
            model_name='hospitalneed',
            name='time_to_reach',
            field=models.CharField(blank=True, help_text='Time within which the donor should reach', max_length=100),
        ),
    ]
