# Generated by Django 5.2.10 on 2026-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_hospitalneed_location_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorderitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='Custom name for the item, used for direct needs', max_length=255, null=True),
        ),
    ]
